ApeWorX/ape-solidity

.gitignore
ape_solidity/compiler.py
tests/conftest.py
tests/contracts/solcontract_2.sol
tests/test_integration.py

fixes: #15 
The source ID is always the same! This violates EIP-2678 and is a bug. It is supposed to be extracted in each iteration of the for-loop.
Use the looped variable path to determine source id rather some variable that just happens to be defined.
ape compile

fix: bug where all compiled source files would have the same source ID

---

.gitignore
README.md
ape_solidity/__init__.py
ape_solidity/compiler.py
setup.py

fixes: #14 
Requires https://github.com/ApeWorX/ape/pull/284 (required to use, not required to install)
Use `import_remappings` kwarg on `solcx` compiler call.
Create the `Dict` of the mappings beforehand using the config item.
If the path does not exist in the config, try appending the `.ape/packages` path to it - if it then exists, use that path.. This is a way to enable a shortcut of using `dependecies:`
https://github.com/ApeWorX/simple-nft/pull/1
^ this compiles

feat: allow configuring import re-mappings

---

ape_solidity/compiler.py

Avoid breaking changes entirely by relying on ethpm-types parsing more

refactor: update to avoid breaking ethpm-types

---

ape_solidity/compiler.py

```
userdoc
value is not a valid dict (type=type_error.dict)
devdoc
value is not a valid dict (type=type_error.dict)
```

fix: broken parsing of ContractType

---

ape_solidity/compiler.py
setup.py
tests/contracts/CompilesOnce.sol
tests/contracts/OlderVersion.sol
tests/contracts/Solcontract.sol
tests/contracts/Solcontract_2.sol
tests/test_integration.py

fixes: #27 
Create a mapping of version to files before running through the  solcx
Compile projects that use multiple Solidity versions.

fix: bug preventing compiling multiple versions

---

ape_solidity/compiler.py
tests/contracts/DifferentNameThanFile.sol
tests/test_integration.py

Regression preventing me from compiling `ds-test` repo.
Smarter, more complex check to findout if input contract types match output
See test!
Also compile the `ds-test` repo or use it as a dependency:
```yaml
dependencies:
- name: ds-test
github: dapphub/ds-test
branch: master
contracts_folder: src
```

fix: bug preventing compiling contracts with different type than file name

---

ape_solidity/compiler.py
tests/conftest.py
tests/contracts/CompilesOnce.sol
tests/contracts/Imports.sol
tests/contracts/folder/Relativecontract.sol
tests/project/ape-config.yaml
tests/project/contracts/Contract.sol
tests/test_compiler.py
tests/test_integration.py

Added logic for fetching referenced imports
partial fix for https://github.com/ApeWorX/ape/issues/623
unblocks @sabotagebeats https://github.com/ApeWorX/ape/issues/81
Read each source path and pull out imports
Add cleaned import strings to dictionary
Ape core implementation https://github.com/ApeWorX/ape/pull/730

fix: ape compile source import references

---

ape_solidity/compiler.py
tests/test_compiler.py

Before, there were some dangling files that got compiled at higher versions as well as their lower, required versions. Now, the dangling sources are removed. This fundamentally  changes nothing except makes it little faster. It is a weird loop, but this ultimately removes all cruft form being passed to the `solc` compiler and seems faster probably because of this. Also, this is a more honest picture of the contract types because now we are using the contract types spit out by the compiler at their most honest levels in relationship to the rest of the project. Now, the project is only compiled with the versions it needs, which usually it just probably a single version, but sometimes there are more challenging repos out there! 😉 
Note: if a single source file is actually requires by …

fix: issue causing unnecessary compilation

---

ape_solidity/compiler.py
tests/ProjectWithinProject/ape-config.yaml
tests/contracts/MultipleDefinitions.sol
tests/test_compiler.py

Issue where if you defined multiple contract types in a single source file, you would only get one of them returned.
Correct version filtering logic to be by contract name instead of source ID to prevent accidental filtering
Can now compile projects that defined multiple contract types in a single source, such as https://github.com/pandadefi/registry/blob/master/contracts/VaultRegistry.sol

fix: issue preventing multiple contact types defined in single source

---

ape_solidity/compiler.py
tests/conftest.py
tests/test_compiler.py

Add logic to install the latest available Solc version if no contracts being compiled include a version
This is specific to a situation where the user is setting up a new project and has not installed Solc themselves
fixes: #51 
Remove Solc installations (I just `rm -rf ~/.solcx/` since I didn't need any right now) and follow steps in #51. With this change it should no longer fail but instead leave you with the latest version of Solidity installed (solc-v0.8.15 in my case)
A test `test_compile_missing_version()` was also added to verify that a system without solidity installed will have the latest version downloaded if the contract being compiled does not specify a version

fix: install latest solc if no pragma-specs found

---

CONTRIBUTING.md
tests/conftest.py

Separated the test suite's solc installations from the user's, which also ensures the tests
start from a clean slate on each run
fixes: #57
Added a session scoped, auto-used pytest fixture for setting the install path at startup and cleaning it up at teardown
Clean out your `~/.solcx` directory, run the tests, and verify that no solc installations are there after the suite completes.
Also should note starting up the test suite may take a tiny bit longer just because it's now downloading the solc binaries when it needs them, rather than relying on the real installations that may be present.

test: use auto-generated solcx install path

---

tests/test_compiler.py

added test for compiler data in manifest
extract compiler data with https://github.com/ApeWorX/ape/pull/871 then test with assertions
ape test

test: compiler data in manifest

---

setup.py

This package is causing warnings to show in tests because it is pinned to an older verison. It is also a dependency in `eth-ape`. I tried to update it there but noticed it broke this plugin because of its own pinning of the package. This PR relaxes the pin so we can upgrade it in ape without breaking it in `ape-solidity`.
Copy what we do for other shared dependencies with `eth-ape`.
Things still work (Tests pass probably suffices).

chore: relax pin on packaging package

---

ape_solidity/compiler.py
tests/test_compiler.py

Changes settings schema to match what is defined here: https://docs.soliditylang.org/en/latest/using-the-compiler.html#input-description
(in the settings key)
* Removed keys that were not in the settings key
* Changed schema / names to align with those docs.
Things still work and settings make sense.

refactor: make settings like settings schema from solidity input JSON

---

.github/ISSUE_TEMPLATE/bug.md
CONTRIBUTING.md
README.md
ape_solidity/_utils.py
ape_solidity/compiler.py
ape_solidity/exceptions.py
tests/test_compiler.py

Allow getting import remappings to filter by the given source paths.
This allows us to remove unused remappings from settings if possible.
Read the lines of the source files and only use remappings from config if present
* Have a bunch of remappings in config e.g.
```yaml
solidity:
import_remapping:
- "@openzeppelin/contracts=OpenZeppelin/4.6.0"
- "@openzeppelin=OpenZeppelin/4.6.0"
- "@solidity-bytes-utils/contracts=solidity-bytes-utils/v0.8.0"
```
* Have a source file only use one of them e.g.:
```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.2;
import "@openzeppelin/contracts/<something>";
contract Contract {
address public owner;
}
```
Check settings and make sure only the 1 shows:
```python
project.extract_manifest().compilers[0].settings["remappings"]
```

fix: issue where sometimes showed unused import remappings in settings

---

ape_solidity/_utils.py
ape_solidity/compiler.py
setup.py
tests/conftest.py
tests/contracts/RandomVyperFile.vy
tests/test_compiler.py

While investigating https://github.com/ApeWorX/ape-vyper/issues/45, noticed an issue with the solidity plugin and vyper files.
The main issue was in ape core and it was fixed there.
This PR adds tests to help ensure bugs don't return
Raise compiler error when non sol files given
Try to compile a vyper file using the solidity compiler:
```python
from ape import compilers
compilers.registered_compilers[".sol"].compile([Path("path/to/vyper/file.vy")])
```

fix: bug where compiler errored in projects with Vyper files

---

ape_solidity/compiler.py
tests/test_compiler.py
tests/test_integration.py

Noticed `--force` was causing import failures when trying to compile the `yearn-vaults` project.
Also, the same failure occurred when compiling a project for the first time with import remappings.
Specifically if you saw this error:
```
5 | import "../../GSN/Context.sol";
```
then it may have been because of this bug.
Ensure the remappings are loaded _before_ setting a variable that grabs all the `.sol` sources for building the import map.

fix: issue where could not force re-compile projects with import remappings

---

.pre-commit-config.yaml
ape_solidity/compiler.py
setup.py
tests/test_compiler.py

The compiler settings should be JSON compliant and follow the standard JSON output format.
There was an issue however where import remappings were a set and thus not JSON encodable.
This fixes that and adds a test.
Convert set to list.
Add test.

fix: issue where remappings in compiler settings were not JSON compliant

---

ape_solidity/_utils.py
ape_solidity/compiler.py
setup.py
tests/contracts/Imports.sol
tests/test_compiler.py

Thank you https://github.com/ApeWorX/ape-solidity/pull/77 for getting this started
fixes: #
* Added the line from the linked PR as a test
* Used a similar while-loop strategy to that of the linked PR
* Mold until test passes
Get multi-line imports and get `get_imports()` and make sure things work out

fix: issue with multi-line import statements

---

.pre-commit-config.yaml
ape_solidity/compiler.py
setup.py
tests/test_compiler.py

As per standard JSON input, the import remappings should be sorted.
Sort remappings and add tests verifying they are sorted in all the right places.

fix: sort remappings in compiler settings

---

ape_solidity/__init__.py
ape_solidity/_utils.py
ape_solidity/compiler.py
tests/BrownieProject/ape-config.yaml
tests/conftest.py
tests/contracts/DirectoryWithExtension.sol/README.md
tests/test_compiler.py

Fixes issue where could not have directory with `.sol` in the name.
Note: It is fixed in 1 spot here and 2 spots in core: https://github.com/ApeWorX/ape/pull/1147
So tests will fail until core is released.
Edit: Make a hack so that it WARNs and still works without the need of an ape core release. So now, the warning will go away after the next release but it is not going to block anyone.

fix: issue when contracts folder contained sub-directories with `.sol` in name

---

.gitignore
ape_solidity/compiler.py
pyproject.toml
setup.py
tests/BrownieStyleDependency/contracts/BrownieStyleDependency.sol
tests/BrownieStyleDependency/contracts/FailingContract.sol
tests/DependencyOfDependency/ape-config.yaml
tests/ape-config.yaml
tests/conftest.py
tests/contracts/Imports.sol
tests/test_compiler.py

fixes: #
Goes with https://github.com/ApeWorX/ape/pull/1152

test: ensure dependencies that don't fully compile are usable

---

ape_solidity/compiler.py
tests/test_compiler.py

* Add and use `srcmap` output.
This stemmed from using Solidity docs to understand Vyper more, regarding `sourcemap`. However, I wanted to see this part work in Solidity to cross-compare and follow the docs. This is mostly part of my research into building coverage features in Ape.
Question: not sure we would want to merge this until we know we will be using this? That is fine if that is the case. I am mostly focused on Vyper right now, as is the plan.
fixes: APE-582
Found the output `srcmap` that gives the source map similarly to `pc_pos_map_compressed` in Vyper.
Is this correct?

feat: add `sourcemap` to `ContractType` output

---

README.md
ape_solidity/compiler.py
tests/conftest.py
tests/contracts/LibraryFun.sol
tests/test_compiler.py

fixes: #43 
Fixes: APE-324
* Allow libraries to be added via `add_library()` method.
* deploy lib in tests
* use `add_library()` method
* deploy contract using lib in tests

feat: adhoc library linking support

---

ape_solidity/compiler.py
setup.py
tests/ape-config.yaml
tests/contracts/Imports.sol
tests/test_compiler.py

fixes https://github.com/ApeWorX/ape/issues/1329
Fixes: APE-688
The early `break` in `get_imports` was the problem
Now, it grabs the most exact match.
can put remappings in any order now.

fix: issue causing wrong remapping to get used

---

ape_solidity/compiler.py

make sure write_test receives a string input.
fixes: #
converting only when needed, using an f-string.
see [PR in my branch](https://github.com/wakamex/ape-solidity/pull/2) that reverts the fix. lots of tests fail without the fix. functional tests pass with the fix:

fix: adding depency crashes when not string [APE-959]

---

ape_solidity/_utils.py
ape_solidity/compiler.py
tests/test_compiler.py

Allows compiling using standard input JSON technique.
This is required to do anything useful with the evm source map output.

feat: standard input JSON support [APE-963]

---

ape_solidity/_utils.py
ape_solidity/compiler.py
setup.py
tests/test_compiler.py

* Get AST data and create objects from ethpm-types for each contract type
For the input JSON, you have to put `"ast"` at the source level; not the contract level, for it to work.
**This means Ape is slightly bloated in that will have duplicate AST info when contracts are stored in the same file.**
this will be needed for contract flattening (i think, based on looking at past implementation), that is why i added it
Can now play with the AST node in contracts.

feat: AST nodes [APE-967]

---

.github/workflows/prtitle.yaml
.github/workflows/publish.yaml
.github/workflows/test.yaml
README.md
pyproject.toml
setup.py

fixes: #
Fixes: APE-994
- change default from 3.8 to 3.10
- update setup.py project tag and supported versions tag
- update readme
- everything works the same on 3.11

feat: python 3.11 support [APE-1038]

---

ape_solidity/compiler.py
tests/contracts/JustAStruct.sol
tests/test_compiler.py

noticed it failed when compiling a project with only a struct in it (the project also was using dependencies)
`.get()`
when compiling only a sol file with no contracts in it, it does not barf out

fix: handle when no contracts in file [APE-1135]

---

ape_solidity/compiler.py

Better error when you type an import wrong and stuff, like this:
```solidity
import "@openzeppelin/contracts/proxy/beacon/IdBeacon.sol";
```
see, i spelled it wrong, and it failed with `FileNotFoundError` which wasn't bad but was kinda unexpected.
If I let it slide to the compiler, the message was really nasty tho.
So here i made it ideal
check for missing files and raise a nice pretty message if you find any.
see my sol example at top

feat: way nicer error when typing an import statement wrong [APE-1152]

---

setup.py
tests/test_compiler.py

this is causing problems and is no longer needed

fix: remove typing extension pin [APE-1209]

---

README.md
ape_solidity/compiler.py
tests/test_compiler.py

Enable compiling contracts with the `--via-ir` solc flag
parse a boolean config value for enabling the `--via-ir` flag. this enables compiling solidity contracts through the Yul IR pipeline. This avoids `stack too deep` errors.
I wrote the affected contract as inline code because if I write it as a contract in the contracts folder, then we have to enable `via_ir` for the whole project, or else all tests fail when compilation is attempted
so I wrote it as inline source, write it to a file, attempt compilation without `via_ir` and check that it fails, and then re-attempt compilation after enabling the  `via_ir` flag.
Add the following config values in a repo with contracts affected by stack-too-deep
```yaml
solidity:
via_ir: True
```

feat: enable via_ir in solidity settings [APE-1256]

---

ape_solidity/compiler.py
setup.py
tests/test_compiler.py

make lazy compiler match
fixes: #
use the built-in `match` function of the pragma_spec to check if an existing (downloaded) solidity spec is a match, and if so use it. this avoids trying to download new solc versions very aggresively, which makes it impossible to compile using ape on an airplane.
turn off your wifi and try to compile anything, without and with this PR.

feat: airplane mode (non-exact compiler version match) [APE-1161]

---

README.md
ape_solidity/compiler.py
setup.py
tests/conftest.py

users were confused how to do this, i realized it was missing from the docs

fix: dependency of dependency auto-version detection [APE-1414]

---

.pre-commit-config.yaml
CONTRIBUTING.md
ape_solidity/_utils.py
ape_solidity/compiler.py
ape_solidity/exceptions.py
setup.py
tests/conftest.py
tests/test_compiler.py

feat: implement compile_code.
NOTE: required patching and releasing py-solx-c like crazy
refactor: switch to packaging.version.Version, also as part of py-solc-x upgrade;

feat: use new settings and implement compile code [APE-1512]

---

.gitignore
README.md
ape_solidity/compiler.py
setup.py
tests/test_compiler.py

fixes: #https://github.com/ApeWorX/ape/issues/1726
* Del ASTNode logic for now as there are no tracing features yet in solidity so this does not affect anything and it was too pre-emptive to add anyway. I would like to get tracing features working and somehing like this is a first step, but the performance concerns leads me to think are going to probably want the raw dicts in the manifest instead and parse them later so compiling alone does not take forever, but will probably adjust `ape-vyper` like that first.
With this PR:
```
(ape310) ➜  ape-playground git:(repro1726) ✗ time ape compile -f
INFO: Compiling 'token.sol'.
INFO: Compiling 'Lib.sol'.
INFO (ape-solidity): Compiling using Solidity compiler '0.8.23+commit.f704f362'.
ape compile -f  4.63s user 0.76s system 122% cpu 4.391 total …
```

perf: remove unused ASTNode parsing

---

ape_solidity/_utils.py
ape_solidity/compiler.py
setup.py
tests/test_compiler.py

Adds support for new `cache_folder` config var which defines where to place non-project dependencies.
Example config:
```yaml
name: ape-project
compile:
cache_folder: .cache
```
Depends on: https://github.com/ApeWorX/ape/pull/1897
Replaces hard references to `.cache` to configuration.  Relies on base_dir for relative paths.
Run against branch from above linked PR.

feat: support configured dependency cache directory

---

ape_solidity/compiler.py
pyproject.toml

use elif in a spot and add a missing python 3.12

chore: add python `312` black value and use `elif` in a spot

---

ape_solidity/compiler.py
tests/NonCompilingDependency/contracts/subdir/SubCompilingContract.sol
tests/ape-config.yaml
tests/contracts/Imports.sol
tests/test_compiler.py

Helps old weird foundry projects using some git submodule nonsense pointing at changed crap, i donno... anyway, ape-solidity can be smarter and just find whatever damn dependency sources you are looking for.. may even help older ape projects work with 0.8. will see

fix: handle missing contracts folder ID in remappings

---

ape_solidity/_models.py
tests/ape-config.yaml
tests/contracts/BuiltinErrorChecker.sol
tests/contracts/Imports.sol
tests/contracts/safe/README.md
tests/contracts/safe/ThisIsNotGnosisSafe.sol
tests/test_cli.py
tests/test_compiler.py

fix: import clash between dependency and relative path

---

.pre-commit-config.yaml
ape_solidity/__init__.py
ape_solidity/_cli.py
ape_solidity/_models.py
ape_solidity/_utils.py
ape_solidity/compiler.py
ape_solidity/exceptions.py
setup.cfg
setup.py
tests/test_compiler.py

prevents losing the momentum in `ape --help`

perf: lazify imports for `ape --help`
