ApeWorX/ape-solidity

.github/release-drafter.yml, .github/workflows/draft.yaml
resolves https://github.com/ApeWorX/ape-solidity/issues/3
followed https://github.com/ApeWorX/project-template/pull/6 as a template
=> reincorporate project template for changelog updates

.github/workflows/test.yaml, ape_solidity/compiler.py, setup.py
fixes: https://github.com/ApeWorX/ape-solidity/issues/6
=> fix: change compile_source to compile_files and refactor

pyproject.toml, setup.py
=> chore: upgrade to eth-ape-0.1.0a26

README.md, ape_solidity/compiler.py, setup.py
=> chore: prepare for beta release

README.md
Update Readme to help out people starting a new project on ape.
fixes: #
=> docs: dependencies update intstrunction

.pre-commit-config.yaml, ape_solidity/compiler.py, pyproject.toml, setup.py, tests/ape-config.yaml, tests/conftest.py, tests/contracts/Solcontract.sol, tests/contracts/Solcontract_2.sol, tests/dependency/contracts/Dependency.sol, tests/test_integration.py
=> fix: issues where remapped paths would override each other

setup.py
=> chore: bump deps

setup.py
Support the `3` range in ethpm-types
=> chore: upgrade ethpm-types

tests/conftest.py
=> fix: test flakeiness

setup.py
Prepare for 0.3.0 release and upgrade ape
=> chore: upgrade ape

.pre-commit-config.yaml, ape_solidity/compiler.py, setup.py, tests/BrownieProject/brownie-config.yaml, tests/BrownieProject/contracts/BrownieContract.sol, tests/VersionSpecifiedInConfig/ape-config.yaml, tests/VersionSpecifiedInConfig/contracts/VersionSpecifiedInConfig.sol, tests/conftest.py, tests/scripts/clean.py, tests/test_compiler.py
fixes: #45 
**This is needed to be able to compile yearn vaults**
=> feat: allow specifying version in ape-config.yaml file

CHANGELOG.md, ape_solidity/compiler.py, setup.py
fixes: #54 
when the user specifies a solc verison and it is not installed, install it first, like we do when grabbing pragma specs
passing build indicates success
=> fix: install specified solc version when it is not installed

.github/workflows/test.yaml, .pre-commit-config.yaml, setup.py
=> chore: bump ape to 0.4

.github/ISSUE_TEMPLATE/bug.md, .github/ISSUE_TEMPLATE/feature.md, .github/ISSUE_TEMPLATE/work-item.md
Adding issues templates for this repo, copied from ape-vyper's
=> fix: add issue templates

ape_solidity/compiler.py, setup.py, tests/test_compiler.py
added get_compiler_settings to ape solidity
with help from @unparalleled-js
=> feat: get compiler settings

.github/workflows/test.yaml, README.md, setup.py, tests/test_compiler.py
=> chore: bump ape

ape_solidity/compiler.py, tests/ape-config.yaml, tests/test_compiler.py
=> feat: support specifying evm_version

.github/workflows/codeql.yml, .github/workflows/prtitle.yaml, .github/workflows/stale-prs.yml, .gitignore, .pre-commit-config.yaml, pyproject.toml, setup.py, tests/ape-config.yaml, tests/contracts/UseYearn.sol, tests/test_compiler.py, tests/test_integration.py
=> chore: 0.6

ape_solidity/compiler.py, setup.py, tests/contracts/HasError.sol, tests/test_compiler.py
=> fix: issue where deploy failures would not enrichment [APE-1142]

setup.cfg, tests/contracts/Imports.sol
Just making sure if we have the same import twice, it ok
import twice
watch tests pass
make sure tests are good
imports are set so that is nice
=> test: ensure duplicate imports does not malfunction [APE-1102]

README.md
Add notes to readme about setting evm version, via config
~~- [ ] New test cases have been added and are passing~~
=> docs: add notes about evm version config to readme [APE-1594]

.mdformat.toml, .pre-commit-config.yaml, README.md, ape_solidity/_utils.py, ape_solidity/compiler.py, pyproject.toml, setup.py, tests/ape-config.yaml, tests/conftest.py, tests/contracts/RandomVyperFile.vy, tests/contracts/SpacesInPragma.sol, tests/test_compiler.py
=> feat!: upgrade to ape 0.7 [APE-1458]

README.md
fixes: #92 
Fixes: APE-794
We actually already did this but adding a quick doc about it
=> docs: document flattening

ape_solidity/compiler.py, tests/test_compiler.py
=> fix(flatten): Warn when multiple licenses instead of failing

.github/workflows/draft.yaml
drafter wasnt updating ,same problem as from other repos
=> chore: write perm missing drafter

.github/workflows/test.yaml, .pre-commit-config.yaml, README.md, ape_solidity/compiler.py, setup.py, tests/conftest.py, tests/test_compiler.py
feat: add support for Python 3.12
chore: update lint dependencies
fix: macos ci issue
docs: add docs to config items
=> feat: add support for Python 3.12

tests/test_compiler.py, tests/test_integration.py
**just checking if CI still passes for ape-solidity, as im seeing some weird things...**
=> test: refactor

ape_solidity/_cli.py, ape_solidity/compiler.py, setup.py, tests/conftest.py, tests/test_cli.py
fixes: https://github.com/ApeWorX/ape/issues/788
fixes: issue where certain import statements were not removed from flattened contract.
feat: add CLI for flattener
=> feat: add contract flattener CLI and fix flattened import logic

.pre-commit-config.yaml, ape_solidity/__init__.py, setup.py
=> chore: fix small lint and performance mistakes
